# Generated by Django 5.1.3 on 2024-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='aadhaar_card',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='iris_image',
            field=models.ImageField(blank=True, null=True, upload_to='iris_images/'),
        ),
    ]
