# Generated by Django 3.1.1 on 2024-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voter_aadhaar_card_voter_iris_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='smartid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
