# Generated by Django 3.1.1 on 2024-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voter_smartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='smartid',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
